### ISSUE TITLE
Elevation Scene Distance Description for Absolute Distance

### ISSUE THREAD

**Issue by SaurabhTotey** [phetsims/number-line-distance#10]
In the elevation scene of NLD, when both point controllers are placed and the distance type is absolute value, the distance description reads `The fish and the bird are [dy] meters apart.`. This distance statement reflects their difference in y-levels, which makes sense in the context of the numberline. However, the fish and the bird aren't actually necessarily that distance apart as they could have different x-levels. In both of the screenshots below, the distance description says they are 1 meter apart when both images have different distances between the point controllers.

This issue doesn't seem major to me, as the intention seems clear regardless, but I was just wondering if this was worth addressing or if maybe there were some better language for describing the difference of their y-values.

![near](https://user-images.githubusercontent.com/22577113/103040020-8f9ad300-452f-11eb-88b7-dffcdecc87ea.png)
![far](https://user-images.githubusercontent.com/22577113/103040022-91649680-452f-11eb-996f-a14b96f85557.png)

**Comment by amanda-phet** [comment]
Hm, that is a very good point. Maybe something like "The fish and the bird have a vertical distance of 1 meter"

https://en.wikipedia.org/wiki/Vertical_position

It doesn't sound great, so I'll have to think about it some more.

**Comment by amanda-phet** [comment]
I asked @arouinfar for her thoughts and she thought maybe "vertical separation" sounded more relative to the other object, where "vertical distance" could sound absolute (as in, distance from the ground). So I'd like to keep that option in mind as well. "vertical difference" could also work. 

I'd like to keep this comment open and in mind when we get to interviews.

**Comment by amanda-phet** [comment]
I conducted two interviews today, and one student in particular noticed that it was the vertical distance between the objects when he had the bird and fish side by side. So far, I am not seeing any issues with the description on this screen.

**Comment by amanda-phet** [comment]
Finished with interviews. I specifically asked a student today about this scene and he correctly interpreted exactly what was happening. I asked because at one point he had the fish and bird just 1-2 m away vertically, but quite far horizontally, and he said "huh". So after the interview, I asked about it, and there was no issue with interpretation.
