### ISSUE TITLE
Documentation Style

### ISSUE THREAD

**Issue by SaurabhTotey** [phetsims/number-line-distance#11]
This issue is just meant to track documentation changes related to https://github.com/phetsims/number-line-operations/issues/54.

**Comment by jbphet** [comment]
While working on #9, I'm seeing a lot of comments that should be fixed up as described in the issue linked above.

**Comment by jbphet** [comment]
Also, I'm noticing a lot of comments that use a different voice than is generally used in PhET code.  For example, in `DistanceShadedNumberLineNode`, there are comments like this,
```
        // makes shading path between nodes
```
...and
```
        // changes shape to arrow if the distance type is directed and the arrow is pointing to a point
        // that is on the number line
```

I understand what's being said here.  Basically, there is an implicit "The following code..." in front of each of these.  But that's not our usual comment style.  Here are some examples from `NaturalSelectionModel`, which is a sim that I did not write:

```
    // organize all graphs under this tandem
```
...and
```
          // Age bunnies, some may die of old age.
```

I guess it's more like these are preceded with "The following code will..."

So, as part of the improvements to the documentation style, these comments should be made more consistent with what is the de facto standard for PhET.
