### ISSUE TITLE
Comments should use the words "number line" instead of "numberline"

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-distance#12]
Parent issue is #9.

My IDE is flagging usages of the word "numberline" everywhere, like so:

![image](https://user-images.githubusercontent.com/3082831/107566371-0eac9f00-6ba2-11eb-8f69-d2d8ccab9428.png)

I looked up the term, and at least according to Webster's dictionary, it should be two words, see https://www.merriam-webster.com/dictionary/number%20line.  It should probably be changed in all comments.

**Comment by SaurabhTotey** [comment]
I believe this issue has been addressed. I cannot find any more examples of "numberline" in comments. Feel free to reopen if I missed something.
