### ISSUE TITLE
Should x and y symbols be translatable?

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-distance#17]
Related to #9 (mid-project code review).

While reviewing the code, I noticed that the x and y symbols used in the distance statement have been made translatable.  We did *not* do this in the Expression Exchange simulation, but I recall that there has been some debate on the topic of whether to make variable names translatable.  What should we do in this case?

Here's a screenshot with no translation:

![image](https://user-images.githubusercontent.com/3082831/108284914-55bb0700-7143-11eb-897a-50206111c380.png)

Screenshot using `stringTest=未知`, which is what Google says in 'unknown' in Chinese:

![image](https://user-images.githubusercontent.com/3082831/108285009-800cc480-7143-11eb-8d7e-ed6225433406.png)

Screenshot for `stringTest=long`:

![image](https://user-images.githubusercontent.com/3082831/108285063-9286fe00-7143-11eb-97a4-b17899f4b24b.png)

Assigning to @amanda-phet for a decision.

**Comment by amanda-phet** [comment]
Yes, variables should be translatable. This is something we are doing moving forward with sims. A few locales (such as Greek and Korean) often use a different symbol for the variable.

**Comment by jbphet** [comment]
Thanks @amanda-phet - I'll leave it as is.  Closing.
