### ISSUE TITLE
Add x1 and x2 labels to point controllers 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#18]
See mockups: 
![image](https://user-images.githubusercontent.com/7852916/111691636-222bd500-87f4-11eb-94a1-21b05faa1580.png)

![image](https://user-images.githubusercontent.com/7852916/111691702-31128780-87f4-11eb-9ca7-04a3e75b68c7.png)

**Comment by SaurabhTotey** [comment]
I added these labels to the sim in a cursory manner, but it seems like something should be done when the points have the same value. Currently, I allow the labels to overlap, but that doesn't look too nice. Perhaps the labels should disappear when the points are at the same location? This doesn't solve issues like the labels still overlapping when the points are really close together in the [-100, 100] scale. Assigning to @amanda-phet to review.

**Comment by amanda-phet** [comment]
Can we add the same semi-transparent white background to these labels as we do for the point labels?

**Comment by SaurabhTotey** [comment]
I added the same semi-transparent background from the point labels to these point names.

**Comment by amanda-phet** [comment]
Looks great! Thank you!
