### ISSUE TITLE
Artwork needs

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#19]
- [ ] sidewalk for the first scene 
- [x] add strokes around the girl and house since they are interactive elements, but leave the backgrounds more flat
- [x] provide background with sky/ocean/boat and just a little bit of waves

**Comment by amanda-phet** [comment]
I think we should remove the waves in this scene and use a transparent blue rectangle over the water. It will partially cover the boat, which really helps with the perspective issue, I think. Here it is with a fish underwater. The sky/boat/water is one layer in the back, with the fish next, and the transparent water layer in the front. 
![image](https://user-images.githubusercontent.com/7852916/112536257-d8eb0080-8d72-11eb-9086-8a11007a2b86.png)

**Comment by amanda-phet** [comment]
Here is the artwork for the first two scenes: 

![hydrant](https://user-images.githubusercontent.com/7852916/118038236-18be7500-b32c-11eb-9e80-55c1f7940b7b.png)
![person](https://user-images.githubusercontent.com/7852916/118038244-19efa200-b32c-11eb-81fe-4cc4d0260566.png)
![house](https://user-images.githubusercontent.com/7852916/118038245-1a883880-b32c-11eb-9af0-a3dec630a00d.png)

![50-C](https://user-images.githubusercontent.com/7852916/118038256-1e1bbf80-b32c-11eb-944f-3199ccd3b6a9.png)
![0-C](https://user-images.githubusercontent.com/7852916/118038257-1e1bbf80-b32c-11eb-8860-7ab7e366cbf1.png)
![-50-C](https://user-images.githubusercontent.com/7852916/118038259-1e1bbf80-b32c-11eb-9fec-4ebc1661904b.png)

**Comment by amanda-phet** [comment]
And the background for the third scene: 

![background](https://user-images.githubusercontent.com/7852916/118040202-853a7380-b32e-11eb-84ef-6fd855fe6831.png)

There is a 900x345 rectangle over the water that is 30% opacity, color: #97C4F2

**Comment by SaurabhTotey** [comment]
I have integrated all the artwork given. Assigning to @amanda-phet to review. One thing of note is that since the background for the elevation scene has the water included, and I'm adding another layer of transparent water above the given background, the water in the scene appears slightly dark. If this is not intended, then it would be useful to get an elevation scene background without the water included since the code adds the water rectangle on top.

**Comment by amanda-phet** [comment]
Thanks @SaurabhTotey . I am liking the color of the water. It matches the image above so I think that's what we want. 

A few tweaks I might like to make though.. 
(1) The house and especially the person seem almost blurry, especially in the panel and legend. Do you have any ideas for how to make those more crisp? (I'm using Safari on an external monitor, if that matters). Sometimes when the resolution is too big they can be blurry, so I could try sending you smaller files. 
(2) Will you try making the road #9b9b9b and see how that looks? I can still make one if needed, but that might be enough to make that work. 
(3) The ice caps, trees, and desert hills should not be the full height. I am going to share new artwork that should make them all the same height in order to make it simpler. Let me know if these will work. They should look roughly like this image below but without the lines/ boxes. 
![image](https://user-images.githubusercontent.com/7852916/118885674-4e77d680-b8b5-11eb-8803-554a278e3d90.png)

New artwork: 
![desert](https://user-images.githubusercontent.com/7852916/118886092-be865c80-b8b5-11eb-9a70-ffb8e85be2e0.png)
![trees](https://user-images.githubusercontent.com/7852916/118886095-bf1ef300-b8b5-11eb-8df1-30254651192e.png)
![antarctic](https://user-images.githubusercontent.com/7852916/118886096-bf1ef300-b8b5-11eb-9d94-6456ec6dd1c6.png)

**Comment by SaurabhTotey** [comment]
I went ahead and implemented points 2 and 3 above. I am unable to see point 1 (the person and the house don't seem blurry to me), but that may be due to the not-terribly-high resolution of the laptop I am using. I did have to scale down the person and the house quite a bit in the code to make them a usable size in the sim, so smaller images may help.

**Comment by amanda-phet** [comment]
Thanks. (2) and (3) look great to me. I might want to improve the appearance of the road still for (2) but I will talk to Megan about that. For (1), let's wait and see how it looks on different devices when we get to QA.
