### ISSUE TITLE
Screen icons

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#20]
Need to make and commit screen artwork

**Comment by amanda-phet** [comment]
These are not official, but we decided we liked this direction: 
![image](https://user-images.githubusercontent.com/7852916/123361957-2707cf80-d52d-11eb-8c79-cd08450cd331.png)

![image](https://user-images.githubusercontent.com/7852916/123361967-2bcc8380-d52d-11eb-9eaa-650c8ba5fc12.png)

TODO:
- [ ] adjust person's hand so the elbow is slightly more bent
- [ ] convert generic screenshot into vector image

**Comment by amanda-phet** [comment]
Here they are! 
Large screen icon: 
![explore-screen-icon](https://user-images.githubusercontent.com/7852916/123470436-a5a65080-d5b1-11eb-8633-80bc6cf74f9e.png)
Navbar icon: 
![explore-navbar-icon](https://user-images.githubusercontent.com/7852916/123470138-39c3e800-d5b1-11eb-8a8c-9c58a90de5f5.png)

Large screen icon: 
![generic-screen-icon](https://user-images.githubusercontent.com/7852916/123470142-3a5c7e80-d5b1-11eb-8ee5-2fbe2cb47809.png)
Navbar icon: 
![generic-navbar-icon](https://user-images.githubusercontent.com/7852916/123470135-3892bb00-d5b1-11eb-853c-8a388d15c365.png)

**Comment by SaurabhTotey** [comment]
I have added the icons, so I will close this issue. Feel free to reopen and reassign if there are new icons or anything else needs to be done.
