### ISSUE TITLE
Make the fish in the legend "swimming"

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#22]
This is minor, but in the third scene, I'd like the fish to be swimming rather than flying. 

Currently, both the bird and fish are flying: 
<img width="188" alt="image" src="https://user-images.githubusercontent.com/7852916/118886367-13c26e00-b8b6-11eb-9e5c-d22a05a76829.png">

**Comment by SaurabhTotey** [comment]
I believe I have fixed this. If there is more work to be done regarding this, feel free to reopen and reassign.
