### ISSUE TITLE
layering of objects can hide one

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#23]
Currently the person can get lost behind the house. I think we have two choices: 

(1) force the person to always be in "front" of the house
(2) Shift the person "down" a little bit so that if they get behind the house, we can grab their feet. We might want to do this in addition to (1) for perspective, since right now they are taller than the door. 

Also, on the temperature scene, the two thermometers can be layered right on top of each other. Can we add a rule that if they are at the same temperature, one gets pushed vertically above or below the other one (depending on space) so that there is always a way to grab the one in the back?

**Comment by SaurabhTotey** [comment]
I have implemented the first two points above. The pushing seems difficult, but I seem to recall something similar in NLI, so I will take a look and see how to go about that.

**Comment by amanda-phet** [comment]
The layering and shifting looks great! I was thinking we'd just do one option, but I'm really liking both.

**Comment by SaurabhTotey** [comment]
I have implemented pushing in the temperature scene. Right now, a thermometer will push the other thermometer when they are the same x-value. The pushed thermometer either gets moved to the top quarter of the temperature area (in terms of height), the bottom quarter of the temperature area (in terms of height), or not at all, depending on which is furthest. Assigning to @amanda-phet to review.

**Comment by amanda-phet** [comment]
For consistency with other sims, and what feels natural to me, the thermometer that you're dragging (further to the front of the z-order) should be the one that jumps out of the way, not the thermometer that we are covering. 

Also, the height of the jump could be a little smaller- try half as far.

**Comment by SaurabhTotey** [comment]
I reworked the thermometer pushing so that the top-layered point controller gets pushed to the side of the temperature area that has more space. The thermometer only gets pushed half as far (1/8th the height of the temperature area) and will only get pushed if the pushing increases the distance between the point controllers.

**Comment by amanda-phet** [comment]
Looks really good to me, thank you
