### ISSUE TITLE
Can we shift the temperature play area down?

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#24]
Right now, the thermometers can cover the information on the number line. It seems like there is room to shift the entire gradient area down. Perhaps line it up with the bottom of the street in the house/person scene? 

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/7852916/118887722-f8586280-b8b7-11eb-9314-51bf854da2ce.png">

**Comment by SaurabhTotey** [comment]
I have shifted the temperature area down. I have currently just hardcoded values for the temperature area bounds such that its bottom happens to align with the bottom of the street in the first scene, so there is nothing in the code that enforces that they are the same. If we change the street's position, it doesn't affect the temperature area bounds, and vice-versa.

Assigning to @amanda-phet to review whether the current modifications to the temperature area bounds are sufficient or if more changes are required.

**Comment by amanda-phet** [comment]
Thanks, this is much better!
