### ISSUE TITLE
Make the distance statement wider

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#26]
I've noticed that the max width for the distance statement leads to a really small font size in this case: 
<img width="383" alt="image" src="https://user-images.githubusercontent.com/7852916/118888093-6dc43300-b8b8-11eb-8d47-17fd9d9b70a7.png">
 

And in other cases, the font size seemed to change slightly, but really didn't seem like a necessary change. I suspect there is a max width for this string and fonts adjust accordingly (as we do for strings). Can we make the string wide enough so that even this statement can maintain the original font size? Perhaps as wide as the blue sky? (for all scenes)

**Comment by SaurabhTotey** [comment]
I have increased the maxWidth for the distance descriptions so that they allows for wider strings before decreasing font size. As far as I can tell, distance descriptions are now no longer decreasing their font size. Assigning to @amanda-phet to review and close if this is resolved.

**Comment by amanda-phet** [comment]
Looks good to me. Thank you!
