### ISSUE TITLE
Polish font size, weight, spacing, and symbols

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#27]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/7852916/118888586-15416580-b8b9-11eb-86ce-4a5a65104a26.png">

<img width="365" alt="image" src="https://user-images.githubusercontent.com/7852916/118888569-0fe41b00-b8b9-11eb-9afc-fe999e24326b.png">

<img width="368" alt="image" src="https://user-images.githubusercontent.com/7852916/118888552-08247680-b8b9-11eb-9936-db5cbd1b96c3.png">

<img width="367" alt="image" src="https://user-images.githubusercontent.com/7852916/118888506-fe027800-b8b8-11eb-9cc8-0323ea435854.png">

I suspect the locations of the values and such are just matching the Generic screen, but I'd like to make some tweaks here to make these all look more normal. If we can find a time to do this on zoom that might be best, but if @SaurabhTotey needs to restructure any code first then just let me know when is a good time to discuss changes here.

**Comment by SaurabhTotey** [comment]
The distance statement now uses the same minus symbol for negatives as it does for subtraction. I have also put some more space after the equals sign. I don't think anything regarding the bolding is being changed, or at least, nothing in the `DistanceStatementNode` code intentionally affects the bolding. Assigning to @amanda-phet to review and point out next steps.

**Comment by amanda-phet** [comment]
Thanks, this is a huge improvement so far with the spacing and negatives. 

It still seems like the subtraction and equal symbols are thinner than the rest. Do you see it here? 
<img width="369" alt="image" src="https://user-images.githubusercontent.com/7852916/122602162-96faef00-d02f-11eb-89d1-51d1080ce974.png">

**Comment by SaurabhTotey** [comment]
Oh, I see what you mean! I think that's caused by a difference caused by using PhetFont for one of those and MathSymbolFont for the other. I'll take a look and see if I can fix it!

**Comment by SaurabhTotey** [comment]
Now the minus and equals signs also use PhetFont so as to match the appearance of the numbers.

**Comment by amanda-phet** [comment]
Thank you! I am really happy with how this looks now.
