### ISSUE TITLE
Move the vertical number line over a little

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#28]
<img width="193" alt="image" src="https://user-images.githubusercontent.com/7852916/119894908-70e3a280-befa-11eb-8776-199ca81a0c69.png">

The y1 and y2 labels are very close to the values on the number line. Can you shift the number line left a little bit? Hopefully the distance between the y1 and y2 labels can match what you have for the x1 and x2 labels on the other scenes.

**Comment by SaurabhTotey** [comment]
I moved this vertical number line to the left a little.

**Comment by amanda-phet** [comment]
Thanks!
