### ISSUE TITLE
Polishes to make more room in play area

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#29]
1. Move scene selection buttons down so that they are centered with the panel, and the same distance between the panel and the reset-all button.

<img width="969" alt="image" src="https://user-images.githubusercontent.com/7852916/119895961-9b822b00-befb-11eb-9e21-4d12ffb58c42.png">

2. Move sidewalk and temperature artwork down (this is 30 px lower in the rough mockup) 

<img width="904" alt="image" src="https://user-images.githubusercontent.com/7852916/119896487-4eeb1f80-befc-11eb-92f0-a1aae64f67ab.png">

**Comment by SaurabhTotey** [comment]
I changed the location of the scene selection buttons to be centered between the right-center of the point controller box and the top-center of the reset button. I also moved the sidewalk and temperature area down a little more.

**Comment by amanda-phet** [comment]
This all looks good to me. Thanks!
