### ISSUE TITLE
Make a dev version for interviews

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#32]
1. We need a dev version asap, since the last version was over 2 months ago. This should be done Friday 6/25/21 regardless of the status of any other polishes or changes to code. 
2. We will need another dev version after implementing artwork and screen icons. This might happen Friday, or another day, but once #31 and #20 are done I'd like a version.

**Comment by SaurabhTotey** [comment]
Alright, https://phet-dev.colorado.edu/html/number-line-distance/1.0.0-dev.2/phet/number-line-distance_en_phet.html is the newest dev version. I will work on integrating #31 and #20 and I'll make a new dev version once those are integrated.

**Comment by amanda-phet** [comment]
We have enough versions now and interview are almost complete.
