### ISSUE TITLE
increase space between radio buttons

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#33]
Can you increase the spacing between these radio buttons, just slightly? 

![image](https://user-images.githubusercontent.com/7852916/123490685-ec0ba780-d5d1-11eb-91ff-8bc3c8efd85c.png)
 

Maybe they could look similar to the spacing of the checkboxes, if that looks ok to you.

**Comment by SaurabhTotey** [comment]
I've increased the spacing. Before, the spacing was using the default value of 3, and I have increased that to 9. Assigning to @amanda-phet to review.

**Comment by amanda-phet** [comment]
Looks great to me! Thank you!
