### ISSUE TITLE
Make objects fly to the play area instead of the panel, if released above the play area

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#34]
A few times in interviews it seemed like students were releasing objects directly on the number line, and the object would fly right back to the panel. That makes me think that in that case, if they are released above the play area (or even to the sides, because the number line is to the left of the bird/fish scene), they should fly to the nearest location in the "play area" rather than fly all the way back down to the panel.

**Comment by SaurabhTotey** [comment]
I have implemented this feature so that in the explore scenes, the point controllers will drop to the play area when above the play area in the first two scenes or to the left of the play area in the last scene. Assigning to @amanda-phet for feedback.

**Comment by amanda-phet** [comment]
Sorry for not replying earlier.. I tested this out right away and thought it looked good, but also noticed a bug that has come with this change and wanted to write it up for you. I'll create a new issue for the bug. Thanks!
