### ISSUE TITLE
Performance Test and Sign-Off

### ISSUE THREAD

**Issue by SaurabhTotey** [phetsims/number-line-distance#37]
Standard code review issue. Created for #35.

**Comment by SaurabhTotey** [comment]
This seems ready for review. Assigning to @amanda-phet to review.

**Comment by KatieWoe** [comment]
@amanda-phet and I were looking at this, and I can take a look if needed, but neither of us are sure what is called for here or what this test entails. Can you please clarify?

**Comment by amanda-phet** [comment]
@SaurabhTotey I just wanted to clarify what you are looking for here. Should I ask @KatieWoe to do a performance test?

**Comment by amanda-phet** [comment]
I'd also like to add that I have this sim open right now from bayes and it's using 70% of my CPU! But I haven't seen issues with past dev versions.

**Comment by SaurabhTotey** [comment]
Oh, my apologies, I wasn't clear at all! I believe you just need to ensure that the performance is adequate for this simulation, or do whatever was done for https://github.com/phetsims/number-line-operations/issues/18. I can make another dev version if that is helpful.

**Comment by amanda-phet** [comment]
@SaurabhTotey I think a dev version would be great. Not urgent, but perhaps when you feel ready to make another one. Thanks!

**Comment by SaurabhTotey** [comment]
Not a problem, I just created https://phet-dev.colorado.edu/html/number-line-distance/1.0.0-dev.5/phet/number-line-distance_en_phet.html.

**Comment by amanda-phet** [comment]
Performance seems just fine!
