### ISSUE TITLE
Review Pointer Areas

### ISSUE THREAD

**Issue by SaurabhTotey** [phetsims/number-line-distance#38]
Standard code review issue. Created for #35.

**Comment by SaurabhTotey** [comment]
Worked with @jbphet to look through pointer areas and make some updates. Assigning to @amanda-phet to review.

**Comment by amanda-phet** [comment]
Can we expand the cursor area (the blue region) for the person? Usually the bounds of the png are fine for a cursor, but in this case the person is quite small. 

![image](https://user-images.githubusercontent.com/7852916/125990513-8440911b-c21e-4d71-840f-00acbe08ae89.png)

Maybe something like this? 
![image](https://user-images.githubusercontent.com/7852916/125990642-ed9413da-15a1-4254-af5d-8d7e8f1bf478.png)

**Comment by SaurabhTotey** [comment]
I have slightly extended the mouse area for the person point controller. Assigning to @amanda-phet to review.

**Comment by amanda-phet** [comment]
Thank you! I think this is a nice improvement.

**Comment by pixelzoom** [comment]
Reopening.  While playing with the sim on a MacBook Pro, I find the thermometers in the Explore screen to be a bit difficult to grab, especialy by their glass tube.  @amanda-phet do you think it would be OK to expand mouseArea for these?

**Comment by pixelzoom** [comment]
The touchAreas for points in the Generic screen look wrong, see below.  I'm guessing that you have an invisible label below the point, which appears when you put a point on the number line.   You can fix this by setting the pointer areas based on visibleBounds instead of localBounds, and adjusting when visibleBoundsProperty changes. 

<img width="411" alt="screenshot_1067" src="https://user-images.githubusercontent.com/3046552/126221295-ba2e18c5-05f5-4cb5-b033-0a56fa6aa9c0.png">

**Comment by amanda-phet** [comment]
>Reopening. While playing with the sim on a MacBook Pro, I find the thermometers in the Explore screen to be a bit difficult to grab, especialy by their glass tube. @amanda-phet do you think it would be OK to expand mouseArea for these? 

Sure! I think it is fine to have those be larger.

**Comment by amanda-phet** [comment]
>The touchAreas for points in the Generic screen look wrong, see below. I'm guessing that you have an invisible label below the point, which appears when you put a point on the number line. You can fix this by setting the pointer areas based on visibleBounds instead of localBounds, and adjusting when visibleBoundsProperty changes.

These touch areas were expanded in previous number line sims so you can easily hold the point a bit lower. I can't remember if it was PhET team members or students in interviews, but someone was having trouble grabbing these, and the expanded areas seem to be working well.

**Comment by pixelzoom** [comment]
> These touch areas were expanded in previous number line sims 

OK! Then please ignore that bit of feedback.

**Comment by SaurabhTotey** [comment]
I have dilated the `TemperaturePointControllerNode`s mouseArea. I'll leave the issue assigned to @amanda-phet.

**Comment by amanda-phet** [comment]
That works for me.
