### ISSUE TITLE
Finalize Credits

### ISSUE THREAD

**Issue by SaurabhTotey** [phetsims/number-line-distance#39]
Standard code review issue created for #35. Should be addressed before publication.

**Comment by pixelzoom** [comment]
As of code review https://github.com/phetsims/number-line-distance/issues/35, the credits are completed empty.  It would be good to take a stab at filling these in before the first dev test.  At this point in the development, you should know everything except QA credits.

**Comment by SaurabhTotey** [comment]
Hey @amanda-phet, an [RC](https://phet-dev.colorado.edu/html/number-line-distance/1.0.0-rc.1/phet/number-line-distance_en_phet.html) was recently created with an attempt at filling out credits. Do these credits look good to you?

**Comment by jbphet** [comment]
When asked about credits for graphic arts, @amanda-phet said (over Slack): 

> Mariah Hermsmeyer, Megan Lai, Amanda McGarry

When asked about other designers, she said:

> Kathy Perkins, Ian Whitacre

**Comment by SaurabhTotey** [comment]
The credits should be complete, I would just like them to be verified.

**Comment by stemilymill** [comment]
> When asked about credits for graphic arts, @amanda-phet said (over Slack):
> 
> > Mariah Hermsmeyer, Megan Lai, Amanda McGarry
> 
> When asked about other designers, she said:
> 
> > Kathy Perkins, Ian Whitacre

Based on this comment, Amanda should be included in the graphic arts credits and she is currently not.

**Comment by KatieWoe** [comment]
I believe QA credits are fine for this
