### ISSUE TITLE
Should variable names and subscripts be translatable?

### ISSUE THREAD

**Issue by SaurabhTotey** [phetsims/number-line-distance#4]
Here are two screenshots from NLD that show variables.
![swap](https://user-images.githubusercontent.com/22577113/88206680-e6f8e800-cc0b-11ea-8e21-650d058a68ba.png)
![distancedescription](https://user-images.githubusercontent.com/22577113/88206685-e95b4200-cc0b-11ea-8eb6-8000d3d1825e.png)
As of this issue, these strings are translatable, but @jbphet is pointing out that we don't always allow translation of these because the translator can mess things up, and translators rarely, if ever, do translate variable names in other simulations when they are translatable. Should these strings be translatable in this simulation?

**Comment by amanda-phet** [comment]
Yes the variables should be translatable, but I'm not sure about the subscripts because I don't think we usually allow numerals to be translated. A few locales have translated variables (Greek is one). 

These strings should also be translatable.

**Comment by SaurabhTotey** [comment]
Alright, currently the variables are translatable but they have the superscript formatting baggage with them. I'll make only the variable letters be translatable and make the subscript formatting with numerals happen in the code and remove those from the translation string.

**Comment by amanda-phet** [comment]
I see. I am not sure what we have done in the past with subscripts.. or if we've ever done something. Maybe check Graphing Lines (the [Arabic](https://phet.colorado.edu/sims/html/graphing-lines/latest/graphing-lines_ar.html) translation, for example) and see what was done there.

**Comment by ariel-phet** [comment]
Looks like the Arabic translation leaves the subscripts alone, and it is not an issue. I agree with leaving the subscripts (which are numerals) non-translatable.

**Comment by SaurabhTotey** [comment]
In my latest commit, I made the subscripts not translatable, but left the variables to still be translatable. I closed this issue, but if further work needs to be done, please reopen!
