### ISSUE TITLE
Add x2 and x1 labels to distance statement

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#40]
In our discussion 7/8/21, we decided that it would be helpful to keep x2 and x1 labels in the distance statement somehow. This is most important in the Explore screen, but ideally it will be in both. 

This is what we are thinking, and to accommodate it on both screens, we might need to make the overall accordion box taller, but not by too much. 

Startup: 
![image](https://user-images.githubusercontent.com/7852916/124980654-e6f72100-dff1-11eb-849c-4f1a7cc67ebc.png)

After dragging one object up: 
![image](https://user-images.githubusercontent.com/7852916/124980684-f1b1b600-dff1-11eb-9a47-d32518d248ea.png)

With two objects dragged up:
![image](https://user-images.githubusercontent.com/7852916/124980715-fb3b1e00-dff1-11eb-82dc-80167e83f79f.png)

Generic screen: 
![image](https://user-images.githubusercontent.com/7852916/124980764-07bf7680-dff2-11eb-8888-008f49f5c461.png)
 

Notice that I made the absolute value bars shorter, and moved that whole statement down to make room for the x2 and x2 labels. The absolute value bars might be a bit short, so that's why I think we might still need to make the accordion box taller, but I'd like to minimize how much larger we make it, so we'll want to shorten those bars for sure.

**Comment by SaurabhTotey** [comment]
Alright, I have added the labels and shortened the absolute value marks. Assigning to @amanda-phet to review.

**Comment by amanda-phet** [comment]
Awesome! I think they look great.
