### ISSUE TITLE
Dropping an object near the number line sometimes results in incorrectly aligned object and dot

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#41]
Related to https://github.com/phetsims/number-line-distance/issues/34 

When I drop an object in this new expanded region (ie, not directly in the final play area), the dot on the number line is often not right where it should be. I do not notice this in the house scene, only in the temperature and bird scenes. 

Here's an example: 
![image](https://user-images.githubusercontent.com/7852916/125989854-62195122-df93-4516-8763-2426a6c4b03a.png)

I dropped the bird near the number line (not in the sky) and the sim detected that the closest location is 20. The bird flies over to the sky, and the dot says 20, but the dot is clearly not in the correct spot on the number line. If I click the bird once, the bird shifts to the integer location, and the dot realigns itself. 

![image](https://user-images.githubusercontent.com/7852916/125989962-e6010069-b0c3-41d4-8c13-d0009126bafb.png)

I am thinking the model needs to pick an integer value and location, so that the objects lands at the correct spot and the dot is in the right spot.

**Comment by SaurabhTotey** [comment]
This was a subtle bug, but I believe the latest commits should now have fixed this. Assigning to @amanda-phet to review.

**Comment by amanda-phet** [comment]
This looks fixed to me. Thanks!
