### ISSUE TITLE
Suggestions for implementation-notes.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-distance#43]
Related to code review, https://github.com/phetsims/number-line-distance/issues/35

implementation-notes.md is generally very good.  A few suggestions for improvements:

- [x] Use uppercase for screen and scene names, because that's how they are labeled.  And you've used uppercase in model.md.  E.g. "...the Explore screen..." versus "...the explore screen..."
- [x] Provide links to  the .js files for sim-specific classes, so the reader can easily navigate to the code.
- [x] Property (uppercase) and property (lowercase) are totally different things. You are using the latter where you should be using the former. 
- [x] Where "number line" is used as an adjective, it is a component adjective, and should be hyphenated. E.g. "The number line is..." vs "The number-line features are..."

**Comment by pixelzoom** [comment]
I made several of these improvements in the above commit, checked off in the checklist above. I'll leave it up to you to decide whether to add links to .js files.

**Comment by SaurabhTotey** [comment]
I added links, so I'll close this issue now.
