### ISSUE TITLE
Review model.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-distance#44]
From https://github.com/phetsims/number-line-distance/issues/35 code review:

> - [ ]  Does model.md adequately describe the model, in terms appropriate for teachers?

This is not something that should be evaluated by a developer.  I typically create an issue, and have the lead designer decide whether the description is sufficient, and in terms that are appropriate for teachers.

I don't see any previous such issue for this sim, so creating this one, and assigning to @amanda-phet.  If you've already reviewed, feel free to close. Otherwise please have a look at [model.md](https://github.com/phetsims/number-line-distance/blob/master/doc/model.md), and provide feedback to @SaurabhTotey.

**Comment by amanda-phet** [comment]
Thanks @pixelzoom . Reviewed and edited. @SaurabhTotey if the changes look ok to you, please close.

**Comment by SaurabhTotey** [comment]
Everything seems good to me!
