### ISSUE TITLE
defaultCelsius query parameter doesn't work.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-distance#45]
For code review https://github.com/phetsims/number-line-distance/issues/35

NLQueryParameter.js has this query parameter:

```js
  /**
   * Query parameter that can be used to make the sim default to Celsius instead of Fahrenheit at startup, added
   * because it has been requested by users in the past (see https://github.com/phetsims/states-of-matter/issues/216)
   * This is public facing.
   */
  defaultCelsius: {
    type: 'flag',
    public: true
  }
```

The documentation indicates that it should start in Fahrenheit, but I couldn't get this to work in NL:D.  With or without `?defaultCelsius`, it always started up in Celsius.

**Comment by amanda-phet** [comment]
Ah, we should not have this query parameter. This sim should always be in Celsius! @SaurabhTotey , can you remove it? 

I suppose we could have this scene in F, with the number line range being -58 to 122, but I think we wanted Celsius so that 0 was always in the center of the number line.

**Comment by pixelzoom** [comment]
Sorry, there's really nothing to remove or change here. I was looking at NLIQueryParameters, thought I was looking at something in number-line-common.    There is no NLDQueryParameters, so this can probably be closed.

**Comment by SaurabhTotey** [comment]
Alright, I'll close this issue then.
