### ISSUE TITLE
Point labels overlap image with stringTest=long

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-distance#46]
For code review #35.

Not sure if this is worth addressing. But with `?stringTest=long` in the Elevation scene, the point labels overlap the picture of the ocean/sky.  

<img width="934" alt="screenshot_1071" src="https://user-images.githubusercontent.com/3046552/126223717-654df298-420a-42f7-ab19-7b52c7502bad.png">

**Comment by amanda-phet** [comment]
These labels should never be longer than 2 characters, so i'm not sure what the best route is to make sure this isn't an issue in the extremely unlikely scenario that someone puts in a long string here. Should we leave this as-is? Or is it better to have a max-width for the string?

**Comment by pixelzoom** [comment]
@amanda-phet said:
> These labels should never be longer than 2 characters

One of those 2 characters is always _x_ or _y_. They are translatable, and there's no way to enforce that they are a single character (because one glyph can require multiple bytes, depending on locale).  

Also note that the penguin can overlap the point label, even in default English, see below.  You have lots of horizontal space to work with, why not use it? 

<img width="259" alt="screenshot_1073" src="https://user-images.githubusercontent.com/3046552/126227039-27cd76fa-85bc-4ed7-a836-c9ae39c72e68.png">

<img width="248" alt="screenshot_1072" src="https://user-images.githubusercontent.com/3046552/126227056-d89a79b4-e499-4f4e-8bdd-90cde3edf620.png">

**Comment by SaurabhTotey** [comment]
I've reduced the maxWidth of the point names so that they no longer overlap with the elevation play area on `stringTest=long`, but I haven't moved the play area or number line yet. I'll leave this issue assigned to @amanda-phet for feedback on what to do.

**Comment by amanda-phet** [comment]
Thanks @SaurabhTotey. Using maxWidth is what I had in mind as a possible fix, but I wasn't sure what all of the options were. 

As for moving the number line.. we can probably move it all over 10px, but not much more because things can get fairly crowded down here
![image](https://user-images.githubusercontent.com/7852916/126555525-4090aaf3-a9de-4e93-905a-b3cf5fc7e7c3.png)

I can really go either way. @SaurabhTotey will you move it over 10px to see how it looks and assign back to me?

**Comment by SaurabhTotey** [comment]
Alright, I moved the elevation scene number line to the left. Assigning back to @amanda-phet.

**Comment by amanda-phet** [comment]
Thanks. That looks good to me!
