### ISSUE TITLE
Improvements to strings file

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-distance#47]
From code review #35:

> - [ ] Make sure the string keys are all perfect, because they are difficult to change after 1.0.0 is published.

Here are some recommend changes.

---

- [ ] "degreesCelsius" value

In number-line-distance-strings_en.json:

```json
  "symbol.degreesCelsius": {
    "value": "° C"
  },
```

(1) There should be no space between '°' and 'C'.  The symbol for "degrees Celsius" is "°C", see https://en.wikipedia.org/wiki/Celsius.

(2) We typically do not put Unicode characters like '°' in files.  We use Unicode escapes, to keep the files UTF8-compatible.

For comparison, here's the same string in gas-properties-strings_en.json:

```js
  "degreesCelsius": {
    "value": "\u00B0C"
  },
```

----

- [ ] "symbol.a" and "symbol.b" keys

```js
  "symbol.a": {
    "value": "A"
  },
  "symbol.b": {
    "value": "B"
  },
```

Highly recommended to change these keys to "symbol.A" and "symbol.B".   Use this convention because (a) it will match what the translator sees on the screen, and (b) some sims have both uppercase and lowercase versions of a character.  For example, in Fourier:

```js
  "symbol.F": {
    "value": "F"
  },
  "symbol.f": {
    "value": "f"
  },
```

**Comment by SaurabhTotey** [comment]
I have implemented both of the suggested changes. I will close this issue.
