### ISSUE TITLE
This sim does not have a color profile.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-distance#48]
For code review #35:
> All sims should have a ColorProfile, named {{PREFIX}}ColorProfile.js, even if they have a single (default)
profile. See https://github.com/phetsims/scenery-phet/issues/642.

While https://github.com/phetsims/scenery-phet/issues/642 is the general issue, I'm creating this sim-specific issue, so that the team can decide whether to create a color profile this late in the game.

Note that there will no longer be a ColorProfile class, and sims should use the new pattern that @samreid has established in  https://github.com/phetsims/scenery-phet/issues/642.

**Comment by pixelzoom** [comment]
Looks like a color profile was added today in https://github.com/phetsims/number-line-distance/commit/1be4c485cba481216878a4a87d5db9d9e689f684/.

**Comment by SaurabhTotey** [comment]
Since there is now a color profile, I will close this issue.
