### ISSUE TITLE
property vs Property

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-distance#49]
For code review #35:
>  Differentiate between Property and "property" in comments. They are different things. Property is a type in AXON; property is any value associated with a JavaScript object. Often "field" can be used in exchange for "property" which can help with clarity. Search for "property" to identify violations.

Code comments appear to refer to "properties" when they mean "Properties".  

This was also flagged in #43 for implementation-notes.md.

**Comment by SaurabhTotey** [comment]
I believe I changed all incorrect usages. I'm closing this issue, but please reopen if I missed anything.
