### ISSUE TITLE
Non-italic subscripts for variables

### ISSUE THREAD

**Issue by SaurabhTotey** [phetsims/number-line-distance#5]
![distancedescription](https://user-images.githubusercontent.com/22577113/88207089-81f1c200-cc0c-11ea-8e48-08ee28bd93c6.png)
![swap](https://user-images.githubusercontent.com/22577113/88207091-8322ef00-cc0c-11ea-92d7-333c530c3410.png)
@amanda-phet had recommended italic variable names with non-italic subscripts. The above is what the variables look like currently. Is this what these should look like?

**Comment by amanda-phet** [comment]
Those look fine to me. Thanks!
