### ISSUE TITLE
Duplication in Scene view classes.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-distance#54]
For code review #35.

There's a bit of dupliction in DistanceSceneView, ElevationSceneView, and TemperatureSceneView. You might consider factoring the commonalities out into a NLDSceneView base class.  

The bits that they have in common are:

* `this.baseView`
* some background imagery
* a `numberLineNode`
* a `pointControllerNodeLayer`
* Their `reset` methods are identical.

Or maybe the base class is as simple as this:

```js
class NLDSceneView extends Node {

  /**
   * @param {NLDBaseView} baseView
   */
  constructor( baseView ) {
    super();

    // @private 
    this.baseView = baseView;
    this.addChild( baseView );
  }
  
  // @public
  reset() {
    this.baseView.accordionBoxOpenedProperty.reset();
  }
}
```

**Comment by SaurabhTotey** [comment]
I made an NLDSceneView as suggested here, but I made the superclass create the `NLDBaseView` and the `DistanceShadedNumberLineNode`. I will close this issue, but feel free to reopen if there is more work to be done.

**Comment by pixelzoom** [comment]
👍🏻 This looks very nice.
