### ISSUE TITLE
Use assert more liberally in the future.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-distance#56]
From code review #35:

> - [ ] ⚠️ Assertions should be used appropriately and consistently. Type checking should not just be done in code comments. Use `Array.isArray` to type check an array.
_@pixelzoom: I'm a little surprised to find only 8 uses of `assert`. But there's only ~2900 lines of code here. Still, I'd encourage you to consider using `assert` more liberally in future code._

I meant to create an issue for this, and just realized that I had not done so.  There's nothing that you need to do for this sim.  You can simply close this issue after reading it.

**Comment by SaurabhTotey** [comment]
Alright, sounds good. I'll keep this in mind for the future. Thanks for the heads up!
