### ISSUE TITLE
Incorrect Wording on Explore tab for Fish and Bird Scene?

### ISSUE THREAD

**Issue by DevonQui** [phetsims/number-line-distance#57]
**Test device**
MacBook Pro

**Operating System**
11.4

**Browser**
Safari

**Problem description**
This is for https://github.com/phetsims/qa/issues/675

In the fish and bird scene of the Explore tab I noticed that Absolute Value Distance Description said "The fish and the bird have a vertical DISTANCE of X meters" whereas the other two scenes are "The house and the person are X meters APART" and "The DIFFERENCE in temperature is X degrees". The other two scenes describe a difference between two values but the fish and bird scene doesn't really seem to do that with the current wording IMO. Was it supposed to say "the fish and the bird have a vertical DIFFERENCE (not distance) of X meters"?

**Steps to reproduce**
1. Open sim
2. Click on Explore tab
3. Click "Absolute Value" in the upper left-hand corner and make sure that the Distance Description is turned on
4. For each of the scenes, drag their respective characters onto the number line and compare how each scene describes the difference between values

**Visuals**
<img width="1245" alt="Screen Shot 2021-07-22 at 12 23 23 PM" src="https://user-images.githubusercontent.com/72042459/126689737-111a670d-954c-4b3c-9197-1e2fcac2febc.png">
<img width="1237" alt="Screen Shot 2021-07-22 at 12 23 10 PM" src="https://user-images.githubusercontent.com/72042459/126689755-ce8bf130-eeeb-477b-ae16-f94d4486abaf.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Distance‬
URL: https://phet-dev.colorado.edu/html/number-line-distance/1.0.0-dev.6/phet/number-line-distance_all_phet.html
Version: 1.0.0-dev.6 2021-07-22 08:01:52 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15
Language: en-us
Window: 1440x792
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by jbphet** [comment]
This seems like a design question.  Assigning to @amanda-phet.

**Comment by amanda-phet** [comment]
Thanks for bringing this up @DevonQui . We definitely struggled with the language in the third scene, but since I specifically made sure students interpreted it correctly in interviews, I'm inclined to leave all of the language as it is. Also, each scene is a new context and needs contextual language, and doesn't need to be 100% the same. 

Closing without making any changes.
