### ISSUE TITLE
Arrow of bottom thermometer can be hard to grab

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-distance#59]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/675. When one thermometer is over another, but lower on the screen, its pointer area can cover the other's arrow, while it still looks grabbable. This can make it hard to grab the intended thermometer.

**Visuals**
![grabunderarrow](https://user-images.githubusercontent.com/41024075/126837335-148a0710-4879-43f6-8692-14282dd8f015.gif)

Troubleshooting information:

</details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Distance‬
URL: https://phet-dev.colorado.edu/html/number-line-distance/1.0.0-dev.6/phet/number-line-distance_all_phet.html?showPointerAreas
Version: 1.0.0-dev.6 2021-07-22 08:01:52 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
Language: en-US
Window: 1280x657
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by SaurabhTotey** [comment]
This issue seems related to https://github.com/phetsims/number-line-distance/issues/58.

**Comment by KatieWoe** [comment]
I'm not sure. I think it has to do with overlapping pointer areas.

**Comment by SaurabhTotey** [comment]
Apologies, I didn't explain myself. If the change to remove the triangle (as proposed in https://github.com/phetsims/number-line-distance/issues/58) goes through, then this issue should also not be problematic if I'm understanding correctly.

**Comment by amanda-phet** [comment]
The pointer areas for the top thermometer is going to be grabbed, so in that video I would expect the green one to be grabbed. Since we removed that triangle, I think this won't be an issue anymore (where the user might expect to be able to grab the triangle that is layered in the back).

**Comment by Nancy-Salpepi** [comment]
I also had the same issue when the bird and fish were overlapping. I thought I was grabbing the fish head, but it moved the bird. When I tried to grab the bird's wing, it moved the fish. Not sure if this is a concern, but I figured I would open the issue again. 

https://drive.google.com/file/d/1hPy369QTlDE_1XyHhtyAv8EPVIcUvDHL/view?usp=sharing

**Comment by amanda-phet** [comment]
@SaurabhTotey is this an issue because the touch areas are rectangular? Can we make custom touch areas that are closer to the shape of the object?

**Comment by SaurabhTotey** [comment]
I talked with @jbphet, and while it is possible to use different shapes for touch areas, it's pretty tricky to use something more elaborate for an image and probably not worth it. This apparently comes up in other simulations as well, and when it's an image, we generally just use rectangular bounds.

**Comment by SaurabhTotey** [comment]
@amanda-phet unless you feel strongly, it seems like nothing will be done on this issue. Let us know your thoughts.

**Comment by amanda-phet** [comment]
Yes I've seen this in other sims as well, and agree we typically use rectangular bounds. Luckily in this sim, we have provided a generous play area to work in, so the objects don't need to be very close to use the sim. Thanks for checking!
