### ISSUE TITLE
Distance statement allows multiple point controllers to have the same value.

### ISSUE THREAD

**Issue by SaurabhTotey** [phetsims/number-line-distance#6]
Up until recently, the distance statement at the top of the generic screen allowed points to have the same value. My current stop-gap for this is to have the point controller 'skip' over the other one if the distance statement would cause them to have the same value. If one point is at 100 and the other is at 99, moving the lower point controller up currently swaps the values of the point controllers (the same happens for -100 and -99).
What should the behaviour for the distance statement be if the user changes the value of one point controller to match the other?

**Comment by amanda-phet** [comment]
Good question. The way the points behave on the number line (on phettest) looks good to me. It reminds me of NLI, how we handled attempting to put points at the same location. Can you review what is done in NLI and see if you're doing the same thing as that sim? 

If the user tries to change the value using the pickers, we could keep doing what you are doing now by skipping the value. I can't see a way to allow the picker to have the same value, unless it was momentary (like the point controllers), but I can't see how that would work. 

Maybe it's time for a design meeting for this sim, to discuss this issue and any others you have questions about?

**Comment by amanda-phet** [comment]
8/27/20 design meeting: 

We'd like to be able to allow overlapping points, and see the distance as 0. So @SaurabhTotey and @jbphet will look into the common code for the point control and see if it's easier to 
(1) make the handle longer
(2) expand the size of the point being covered

And pick one to implement as feedback in the case when two points overlap.

**Comment by jbphet** [comment]
I'm going to unassign myself from this issue and focus on the one for "Number Line: Operations", since that sim will likely be published first.  I'll keep in mind that the solution we come up with will need to work well in both that sim and this one.

**Comment by SaurabhTotey** [comment]
I did a brief investigation of what would need to happen to make these changes possible.

For option 1, the relevant changes would involve NLC's `PointController.offsetFromHorizontalNumberLine` and `PointController.offsetFromVerticalNumberLine`. To have those values be able to change (when the point controllers overlap), those fields would need to ostensibly change from numbers to NumberProperties and be changed from being private to being public. Then, any behaviour that uses those fields would need to be linked to the property.

For option 2, a similar change would instead be required for `PointControllerNode.draggableNode`. Currently that field is private, but there would need to be some way of changing the field and having the PointControllerNode update. With that change, we would be able to replace the existing ShadedSphere with a larger ShadedSphere. ShadedSphereNode could instead be changed to have a modifiable radius, but I don't personally like that idea.

I'll try experimenting with these changes and see if I can get demos of both.

**Comment by SaurabhTotey** [comment]
I have made some progress with getting the handle lengths to change when points overlap in the OverlapAttachDistance branches of NLC and NLD, but the behaviour as it is right now is extremely buggy. I am having a bit of trouble finding the causes for any of the issues at this moment.
However, enough of it is implemented that it should be usable for a demo. I'll now pivot to making a demo for expanding the shaded sphere when point controllers overlap.
Once I have that implemented in some basic form, I'll get dev-versions published for each demo. Then I can try ironing out the issues for whichever option is chosen.

**Comment by amanda-phet** [comment]
Discussed 3/18/21 and decided to "do nothing" for right now and see how this does in interviews. For now, there are at least some cues in the sim that the two points are at the same location. 

We do still need to make sure the description says "x2 and x1 are 0 units apart" in this case of overlapping points.

**Comment by jbphet** [comment]
Added the "deferred" label based on the decision documented above.

**Comment by amanda-phet** [comment]
Removing deferred for now because @SaurabhTotey still needs to complete this: 

> We do still need to make sure the description says "x2 and x1 are 0 units apart" in this case of overlapping points.

**Comment by SaurabhTotey** [comment]
When adding this feature, I realized why I originally just left out a description for 0 distances: for directed distances, the string template depends on whether the subtraction statement is positive or negative, and I didn't know which to use when the distance was 0. For example, in the water scene, if the statement is positive, the description will say `y_2 is * meters above y_1`, or if the statement is negative, the description says `y_2 is * meters below y_1`, and I didn't know which one to select when the distance was 0. The water scene uses `above` and `below` to denote the direction, the temperature scene uses `hotter` and `colder`, the first explore scene uses `east` and `west`, and the generic screen uses `more positive` and `more negative`.

Right now, I made small modifications to the code that so that it uses the absolute value distance string template when the distance is 0, regardless of whether the user has the `Directed Distance` radio button selected. In the water scene, this means that a 0 distance right now will always read as `y_2 and y_1 have a vertical distance of 0 meters`, regardless of whether the user was looking at absolute values or directed distances.

An alternative way I can do this is to default to the positive statement string template whenever the distance ends up being 0 and the user is in the `Directed Distance` mode. In such a scenario, a 0 distance will be described as `y_2 is 0 meters above y_1` in the water scene.

Assigning to @amanda-phet for feedback.

**Comment by amanda-phet** [comment]
>Right now, I made small modifications to the code that so that it uses the absolute value distance string template when the distance is 0, regardless of whether the user has the Directed Distance radio button selected. In the water scene, this means that a 0 distance right now will always read as y_2 and y_1 have a vertical distance of 0 meters, regardless of whether the user was looking at absolute values or directed distances.

@SaurabhTotey this sounds like a perfect way to handle the string when the two points are in the same location! 

I'll change the status of this issue so that I can see how users interpret point controllers at the same value.

**Comment by amanda-phet** [comment]
Conducted 2 interviews today, and there was no issue when the two point controllers had the same value. They seemed to interpret it perfectly.

**Comment by amanda-phet** [comment]
Interviews are now complete and I didn't see any issues here!
