### ISSUE TITLE
Layering house and fire hydrant causes fire hydrant to be partially hidden by shrub

### ISSUE THREAD

**Issue by stemilymill** [phetsims/number-line-distance#60]
For https://github.com/phetsims/qa/issues/675.

In the Explore screen, house & person scene, the house being placed at -1 or 1 causes all but the very bottom of the fire hydrant to be hidden by the bush part of the house icon. 

Should the fire hydrant be completely hidden when the house is in those locations? Or should the fire hydrant be in front of the house / just behind the sidewalk?

![house overlap fire hydrant makes hydrant visible underneath bush](https://user-images.githubusercontent.com/85511101/127030759-9595ead4-fa61-4b96-8cba-1433c2575d9f.jpg)

**Comment by amanda-phet** [comment]
@SaurabhTotey could we nudge the hydrant up a few pixels so that it will be completely covered by the shrubs in this case?

**Comment by SaurabhTotey** [comment]
I moved the fire hydrant up so that it no longer visible under the shrubs when the house is partially covering it. I will close this issue, but feel free to reopen if there is anything more that needs to be done.
