### ISSUE TITLE
Thermometers cover x1 and x2 labels

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-distance#61]
https://github.com/phetsims/qa/issues/683

Since the pointers were removed, the thermometers now have the ability to cover the x1 and x2 labels below the number line. 

<img width="559" alt="Screen Shot 2021-08-02 at 8 21 11 AM" src="https://user-images.githubusercontent.com/87318828/127861817-5d449a9c-ec7e-4198-a8d1-998ab80430fb.png">

**Comment by amanda-phet** [comment]
I knew this would be possible, and it's related to a change we made in https://github.com/phetsims/number-line-distance/issues/24 . I don't think we want to create even more space between the number line and play area (or else they seem too disconnected) so I am ok with this edge case. There are other ways to know which one is x1 and x2, in this case. 

Thanks for documenting this @Nancy-Salpepi
