### ISSUE TITLE
Black dot appears on the left side of description statement when distance between balls changes from 0 to 1

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-distance#62]
**Test device**
MacBook Air (M1 chip)

**Operating System**
11.4

**Browser**
safari 14.1.1

**Problem description**
https://github.com/phetsims/qa/issues/683

When moving one of the balls up/down so that the distance between the balls changes from 0 to 1 (or 2-->1 or 10-->9), a black dot appears on the screen at the beginning of the distance description. It seems to be the black dot on the tail of the "y" because I can toggle so that the tail of the "y" is missing that dot (both can be seen in video). I have also been able to get 2 dots (see pic) and I have been able to get 1 dot when the horizontal axis is used as well. 

**Steps to reproduce**

To reproduce the dot in front of the "y" in the distance description:
1. Select the generic screen 
2. Place the 2 dots on the number line
3. Press the vertical number line button
4. Move one dot until you are toggling back and forth so that the distance between them is either 1 or 0. 

To reproduce the "y" missing a dot on its tail in the distance description:

1. Follow the 4 steps above
2. In the combo box, select the scale "-100 to 100"
3. Move one of the dots until you are toggling back and forth so that the distance between them is either 1 or 0.

**Visuals**
https://drive.google.com/file/d/1Gz1JcVdEhiKNsmKo3lonGm0JOZRttkG-/view?usp=sharing

<img width="412" alt="Screen Shot 2021-08-02 at 3 56 02 PM" src="https://user-images.githubusercontent.com/87318828/127919933-c7257339-6408-46f8-a7cd-063d60e825ae.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Distance‬
URL: https://phet-dev.colorado.edu/html/number-line-distance/1.0.0-rc.1/phet/number-line-distance_all_phet.html
Version: 1.0.0-rc.1 2021-07-30 16:56:03 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15
Language: en-us
Window: 1111x683
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by Nancy-Salpepi** [comment]
Also seen using my iPhone

**Comment by samreid** [comment]
It looks like the “y” draws part of the tail outside its bounding box, so that area is not marked for repaint.

**Comment by samreid** [comment]
May be related to usage of MathSymbolFont?

**Comment by amanda-phet** [comment]
https://github.com/phetsims/scenery-phet/issues/689 was created to track this scenery-phet issue. This issue does not block publication, and will hopefully get resolved later on a global scale.
