### ISSUE TITLE
x1 and x2 labels overlapping tick mark labels in the explore screen

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#66]
@stemilymill wrote: 

Another instance of x labels overlapping other things is in the explore screen, for the house/girl scene and thermometer scene, the x labels overlap the 0 on the number line.

![x1 x2 labels overlap number line numbers zoom](https://user-images.githubusercontent.com/85511101/128224257-0765d921-ad7b-4bcb-b74e-e6c337f74c55.jpg)

_Originally posted by @stemilymill in https://github.com/phetsims/number-line-distance/issues/63#issuecomment-892827027_

**Comment by amanda-phet** [comment]
For these overlaps, I am wondering why the height of the x1 and x2 labels is so tall, especially above the variable. I think we can move these labels down if needed, but I would like to do a combination of first reducing the height of the label (if possible) and then shifting down if we still need more room to not overlap the 0. 

For example, this looks like a totally reasonable size for the background of these labels: 
![image](https://user-images.githubusercontent.com/7852916/128426302-762ceb51-35b5-4f75-ae76-5a1d67f9dad4.png)

And then we can move them down a couple pixels so they don't overlap with the 0. 

To be clear- this change can be applied universally: all screens and scenes.

**Comment by amanda-phet** [comment]
I might not be able to review this when it gets fixed, so if this change happens after August 7th please assign back to @stemilymill and also to @kathy-phet .

**Comment by SaurabhTotey** [comment]
I also found it odd how the backgrounds were a little too tall for the texts. I fixed this by forcing the texts to accurately compute their own bounds (as suggested by @jbphet). I also moved the point names down so that they no longer overlap with the number line numbers. Assigning to @stemilymill and @kathy-phet for review.

**Comment by kathy-phet** [comment]
Looks good to me! Thanks for the fix @SaurabhTotey.

**Comment by samreid** [comment]
Should this be cherry-picked into the RC branch?

**Comment by kathy-phet** [comment]
Yes, this should be in the 1.0 published version. I assume @jessegreenberg will help @SaurabhTotey with this process when rc.2 is published for spot checks.

**Comment by jessegreenberg** [comment]
@SaurabhTotey cherry-picked this change into the release branch, ready for verification by QA.
