### ISSUE TITLE
point labels and distance label overlap more than necessary in bird scene

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#67]
@stemilymill wrote: 
In the fish and bird scene, the point labels and distance labels can also overlap.

![ipad number label overlap distance label](https://user-images.githubusercontent.com/85511101/128396100-f8490226-71db-4712-a80d-d69bc3d2d567.png)
(I messed with the color balance etc to make it more visible)

iPadOS version: 14.7.1

_Originally posted by @stemilymill in https://github.com/phetsims/number-line-distance/issues/63#issuecomment-893651843_

**Comment by amanda-phet** [comment]
For this, I think it would be a good idea to move the distance label a tiny bit to the left so it's not overlapping the point labels.

**Comment by SaurabhTotey** [comment]
I have moved the distance text to the left for the elevation scene. Assigning to @amanda-phet.

**Comment by amanda-phet** [comment]
Looks great! Thanks!
