### ISSUE TITLE
Rename "directed distance" behind a query parameter

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-distance#68]
A physics teacher on twitter recommended the change to "displacement", and Ariel suggested we add this an an option behind a query parameter. I'm wondering if we would want it to be a query parameter, or instead maybe an option in the preferences menu. Assinging to @kathy-phet to discuss.

**Comment by kathy-phet** [comment]
We often both, in cases like this. So its in the preferences, but initial selection can be controlled by query parameter.

**Comment by amanda-phet** [comment]
Thanks @kathy-phet . Should we try to re-publish the sim soon with this feature? Or wait until there's another reason to re-publish?

**Comment by marlitas** [comment]
I think this is the perfect time to include this feature! Assigning to me and @Luisav1 for whoever can get to it first.

**Comment by marlitas** [comment]
Discussed with @amanda-phet we will use a query parameter flag `displacement`. This will replace the text "Directed Distance" with "Displacement".

**Comment by kathy-phet** [comment]
Is this becoming a sim-specific setting in Preferences dialog?

**Comment by marlitas** [comment]
When talking with @amanda-phet it sounded like we were only doing it as a query parameter, not a sim-specific preference.

**Comment by amanda-phet** [comment]
@kathy-phet would you like it to be added to Preferences? I'm not sure how involved that is, but @marlitas can probably weigh in.

**Comment by marlitas** [comment]
It's not that involved. I would assume we just want that to be a toggle control.

**Comment by amanda-phet** [comment]
@marlitas and I discussed and would like this in the Simulation tab of the preferences dialog. I think a radio button is more appropriate since it's really a choice of two different labels, not a toggle where we are turning something "on." 

It can look something like this: 
![image](https://github.com/phetsims/number-line-distance/assets/7852916/4ccfab90-8b67-4fb0-83f9-05e75284fabf)

Control label: Terminology
Options: 
* Directed distance
* Displacement

**Comment by amanda-phet** [comment]
Looks good. I'd like to add a description to this preference. Can you include this description: Choose the terminology used to describe the difference between two integers.

**Comment by marlitas** [comment]
@amanda-phet, the description has been added. Let me know what you think, and close if all looks well.

**Comment by amanda-phet** [comment]
Looks good. Thanks!
