### ISSUE TITLE
Nav bar icons and other artwork look fuzzy on lower resolution monitors

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-distance#72]
On my main monitor, the nav bar icons and the artwork on the lower right of the screen look fine, but they look quite fuzzy on my auxiliary monitor.  It might be wise to turn these into mipmaps to make them look a little better in all situations.

Here is a screenshot taken from the auxiliary monitor.

![image](https://user-images.githubusercontent.com/3082831/138740408-a1ee9e6b-33bb-4508-957a-13dcc2b5dc76.png)

**Comment by marlitas** [comment]
I believe we can tackle this in this upcoming publication while adding character sets.

**Comment by marlitas** [comment]
@jbphet We would like to address this, but I haven't worked with mipmaps before. Do we just need to upload a higher resolution png of each image to avoid some of the fuzziness?

**Comment by jbphet** [comment]
Yes, at least I think so.  In other words, I believe that higher resolution images would probably improve the situation, but you'd need to try it and do some testing to be sure.

**Comment by marlitas** [comment]
@amanda-phet and I noticed that moving the images out of a mip-map made the icons much crisper. We are going that route for this initial dev test, and will have QA keep an eye on any discrepancies moving forward.

**Comment by Nancy-Salpepi** [comment]
I didn't see anything blurry for https://github.com/phetsims/qa/issues/1005 on the platforms  I tested.

**Comment by marlitas** [comment]
Okay great. I'm going to mark this issue as complete then and close. Thanks!
