### ISSUE TITLE
Add Africa, Africa - conservative, Asia, and Latin America character sets

### ISSUE THREAD

**Issue by Luisav1** [phetsims/number-line-distance#74]
First need to add a preference model and then we'll add the classes and structure for the character sets.

**Comment by marlitas** [comment]
I believe this is ready for artwork.

**Comment by amanda-phet** [comment]
I uploaded the characters at the same widths. Hopefully that helps with integrating them. They are all different heights so we should make sure that looks ok in the sim.

**Comment by marlitas** [comment]
The characters have been added in. There was some quirkiness with the heights, but I think I figured out a good layout strategy that we can use in future sims as well. This is ready for @amanda-phet to review for character visuals and behavior. I believe we still need to add in the screen icons though.

**Comment by amanda-phet** [comment]
Screen icons are uploaded. 

The characters look pretty fuzzy :( Should I export them at a higher resolution? Or did this sim maybe use mipmaps to handle that?

**Comment by marlitas** [comment]
The characters are handled through mipmaps. I'm not sure what the process is of deciding when to use mipmaps or not...

**Comment by marlitas** [comment]
The fuzziness is being handled in https://github.com/phetsims/number-line-distance/issues/72. Closing this issue as completed.
