### ISSUE TITLE
Visual differences between Published and version on main

### ISSUE THREAD

**Issue by marlitas** [phetsims/number-line-distance#76]
With the dynamic layout conversion there are a couple of visual differences that are present right now. This can be fixed, but I think it would be good to meet synchronously with @amanda-phet first to discuss them and gauge thoughts.

**Comment by amanda-phet** [comment]
@marlitas did we review these already?

**Comment by marlitas** [comment]
Yes we did! This was the issue that I couldn't find. Ends up I just didn't add it to the project board. well. We hit it anyways, so closing.
