### ISSUE TITLE
Y variables missing from scene 3

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-distance#77]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.1

**Browser**
Safari 17.1

**Problem description**
For https://github.com/phetsims/qa/issues/1005, the y variables are missing from scene 3 of the Explore screen. 

**Visuals**
Dev version:
<img width="395" alt="Screenshot 2023-11-21 at 8 03 37 AM" src="https://github.com/phetsims/number-line-distance/assets/87318828/cd6555cb-542b-4947-8f67-cd324d30570e">

Published:
<img width="395" alt="Screenshot 2023-11-21 at 8 03 53 AM" src="https://github.com/phetsims/number-line-distance/assets/87318828/e2395a0e-ce52-4634-bef5-4037ede19145">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Distance‬
URL: https://phet-dev.colorado.edu/html/number-line-distance/1.1.0-dev.2/phet/number-line-distance_all_phet.html
Version: 1.1.0-dev.2 2023-11-20 22:12:27 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15
Language: en-US
Window: 1378x688
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by KatieWoe** [comment]
Also on the Generic screen if you switch the numberline to up and down.
![also](https://github.com/phetsims/number-line-distance/assets/41024075/685e8744-464f-4ef5-835e-546bf5fdd4c2)

**Comment by marlitas** [comment]
This was addressed in the above commit. Over to @Nancy-Salpepi or @KatieWoe to confirm on main. Close if all looks well!

**Comment by KatieWoe** [comment]
Looks good to me
