### ISSUE TITLE
Non moving toolbox

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-distance#78]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1005
When you switch the number line to an up and down orientation on the Generic screen, the tool box does not move, though the dots do. The tool box overlaps with the line.

**Visuals**
![also](https://github.com/phetsims/number-line-distance/assets/41024075/817fab61-21f5-4c0f-9de5-14b450e01d7e)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Distance‬
URL: https://phet-dev.colorado.edu/html/number-line-distance/1.1.0-dev.2/phet/number-line-distance_all_phet.html
Version: 1.1.0-dev.2 2023-11-20 22:12:27 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language: en-US
Window: 1536x707
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by marlitas** [comment]
I eliminated code that was updating the rectangle in a quick layout change, the above commit restores that logic. @KatieWoe can you check on main and close if all looks well?

**Comment by KatieWoe** [comment]
Looks good
