### ISSUE TITLE
Points off Scale panel can be offscreen in some locales

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-distance#83]
**Test device**
MacBook Air M1 chip/Dell

**Operating System**
14.1.1/Win10

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1005, I noticed that the "Points off Scale!" string wasn't translated in 1.1.0-dev.2. 
On main, that problem seems to be fixed, but the panel on the right side no longer aligns with the right edge of the number line. 
This causes the panel to sometimes be cut off with certain locales and smaller screen sizes. 

**Steps to reproduce**
Here is an example:
1. In main, change the locale to Slovencina. 
2. On the Generic screen, place a ball on the number line
3. Increase the ball's value until the "Points off Scale!" statement appears.

**Visuals**
on Main:
<img width="269" alt="Screenshot 2023-11-27 at 3 21 50 PM" src="https://github.com/phetsims/number-line-distance/assets/87318828/9ead04d3-f85a-46a4-a1d9-b4b94a1b5914">

Published:
<img width="269" alt="Screenshot 2023-11-27 at 3 21 37 PM" src="https://github.com/phetsims/number-line-distance/assets/87318828/44c84141-1987-4415-b725-5c6df1736571">

On main with the iPad:
<img width="172" alt="Screenshot 2023-11-27 at 3 24 09 PM" src="https://github.com/phetsims/number-line-distance/assets/87318828/4d51d9a6-0fc2-4a44-9155-efee3acc3eb9">

**Comment by Nancy-Salpepi** [comment]
@marlitas it does happen. 
Sorry....my order of steps isn't right. 
Change the locale last:


1. In main, on the Generic screen, place a ball on the number line
2. Increase the ball's value until the "Points off Scale!" statement appears.
3. Change the locale to Slovencina.

**Comment by marlitas** [comment]
That did the trick! Thanks @Nancy-Salpepi. This is now ready to check on main. Feel free to close if all looks well.

**Comment by Nancy-Salpepi** [comment]
Looks good @marlitas!!
