### ISSUE TITLE
Should touch/pointer areas be the same width for checkboxes?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-distance#85]
For https://github.com/phetsims/qa/issues/1009 I have the same question as in https://github.com/phetsims/number-line-integers/issues/124.
Wondering if the touch/pointer areas for checkboxes should all be the same width?
<img width="269" alt="Screenshot 2023-12-08 at 9 31 26 AM" src="https://github.com/phetsims/number-line-distance/assets/87318828/f9c0295f-3896-4f96-8117-f92c5c597613">

**Comment by marlitas** [comment]
This was fixed in: https://github.com/phetsims/number-line-integers/issues/124. Should be cherry picked here as well.

**Comment by marlitas** [comment]
cherry picked for https://github.com/phetsims/qa/issues/1018. Feel free to close if all looks well.

**Comment by Nancy-Salpepi** [comment]
The touch area and the pointer area are the same size now but the area for each checkbox is still different. 
I thought the areas for each checkbox were usually the same size (a short word would have a touch/pointer area that is the same size as a long word), but maybe that isn't standard?
Feel free to close if that is not the case. 
Ex. CaV:
<img width="152" alt="Screenshot 2023-12-21 at 8 53 02 AM" src="https://github.com/phetsims/number-line-distance/assets/87318828/6101a312-212e-4a80-970f-4c4b711625b4">

**Comment by marlitas** [comment]
I believe that's the case when using VerticalCheckboxGroup which the Number Line sims do not use. I don't believe that's prohibitive here, although it may want to be refactored in the future it was outside the scope of this publication to address full refactors like that. Closing.
